# Generated by Django 5.0.7 on 2024-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
    ]
