# Generated by Django 4.2.13 on 2024-08-11 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0002_record_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'permissions': [('ca_add_client', 'Может добавлять клиента'), ('can_change_client', 'Может изменять клиента'), ('can_view_client', 'Может просматривать клиента')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('can_add_record', 'Может добавлять запись'), ('can_change_record', 'Может изменять запись'), ('can_view_record', 'Может просматривать запись'), ('can_delete_record', 'Может удалять запись')], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterField(
            model_name='record',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='record',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=300, verbose_name='Диагноз')),
                ('test', models.CharField(max_length=200, verbose_name='Тест')),
                ('result', models.CharField(max_length=150, verbose_name='Результат')),
                ('units_of_measurement', models.CharField(max_length=100, verbose_name='Единицы измерения')),
                ('proper_values', models.CharField(max_length=100, verbose_name='Должные значения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.client', verbose_name='Клиент')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.record', verbose_name='запись')),
            ],
            options={
                'verbose_name': 'диагностика',
                'verbose_name_plural': 'диагностики',
            },
        ),
    ]
